  <link rel="stylesheet" href="assets/css/theme_0/bootstrap.min.css">
  <link rel="stylesheet" href="assets/css/theme_0/flaticon.css">
  <link rel="stylesheet" href="assets/css/theme_0/slicknav.css">
  <link rel="stylesheet" href="assets/css/theme_0/animate.min.css">
  <link rel="stylesheet" href="assets/css/theme_0/magnific-popup.css">
  <link rel="stylesheet" href="assets/css/theme_0/fontawesome-all.min.css">
  <link rel="stylesheet" href="assets/css/theme_0/themify-icons.css">
  <link rel="stylesheet" href="assets/css/theme_0/slick.css">
  <link rel="stylesheet" href="assets/css/theme_0/nice-select.css">
  <link rel="stylesheet" href="assets/css/theme_0/style.css">
